- bootcamps/makersquare/programs/primary/data.yml
- topics.yml
Companion PR: https://github.com/Thinkful/chickadee/pull/43
> Consolidate angular and angular-js topics

- bootcamps/level/programs/data-analytics/data.yml
Hi! Thanks for getting the initial listing up so quickly, much appreciated.
Would you be able to share why the topics got pulled last time and `data-analytics` changed to `data-science`? This information isn't as accurate in describing the program, as we don't teach python or train towards data scientists but data analysts.
Any guidelines we're bumping up against we'd be happy to adhere to, we're just looking to give as accurate a description as possible. Thanks again and we appreciate the work you're doing!
Feel free to reach out to juliana [at] leveledu [dot] com or on this PR.
> Updates to Level Bootcamp

- bootcamps/iron-yard/data.yml
- bootcamps/iron-yard/description.md
- bootcamps/iron-yard/programs/c-and-net/data.yml
- bootcamps/iron-yard/programs/data-science/data.yml
- bootcamps/iron-yard/programs/front-end-engineering/data.yml
- bootcamps/iron-yard/programs/java-and-clojure/data.yml
- bootcamps/iron-yard/programs/mobile-engineering/data.yml
- bootcamps/iron-yard/programs/python-and-django/data.yml
- bootcamps/iron-yard/programs/rails-engineering/data.yml
- bootcamps/iron-yard/programs/user-interface-design/data.yml
Updated description and courses!
> Updates for The Iron Yard

- bootcamps/code-fellows/programs/advanced-software-development-in-full-stack-javascript/data.yml
- bootcamps/code-fellows/programs/advanced-software-development-in-ios/data.yml
- bootcamps/code-fellows/programs/advanced-software-development-in-python/data.yml
- bootcamps/code-fellows/programs/foundations-of-software-development/data.yml
- bootcamps/code-fellows/programs/intermediate-software-development/data.yml
- bootcamps/code-fellows/programs/intro-to-software-development/data.yml
attempting to fix https://circleci.com/gh/Thinkful/blackbird/457
> attempt #4

- bootcamps/code-fellows/programs/advanced-software-development-in-full-stack-javascript/data.yml
- bootcamps/code-fellows/programs/advanced-software-development-in-ios/data.yml
- bootcamps/code-fellows/programs/advanced-software-development-in-python/data.yml
- bootcamps/code-fellows/programs/intermediate-software-development/data.yml
- bootcamps/code-fellows/programs/intro-to-software-development/data.yml
https://circleci.com/gh/Thinkful/blackbird/463
> Attempt #9

- topics.yml
Testing out allowing topic pages to have unique descriptions
> add topic descriptions

- bootcamps/the-iron-yard/description.md
6 scholarships added in unordered list, please QA how it displays
> Add scholarship

- bootcamps/founders-and-coders/description.md
> Added application link

- topics.yml
step 1: identify meta-description (don't merge until descriptions are added and system is set up to handle this new thing)
> Add topic descriptions, meta-descriptions

- bootcamps/thinkful/programs/flexible-web-development-bootcamp/data.yml
> Add TF to Raleigh-Durham and Atlanta

- cities.yml
58 `description`
20 `meta_description`
> Added descriptions and meta_descriptions for cities.yml

- cities.yml
Not having a slug for greenville is breaking everything
> add slug for greenville

- bootcamps/sabio/programs/full-stack/data.yml
I noticed we could be more verbose in the scholarships line so i added some clarity.
I also added node as a skill we train
> changing the scholarships and adding in node

- bootcamps/thinkful/data.yml
> update program name

- cities.yml
To make it easier to match when searching for recommendations
> add city aliases

- bootcamps/thinkful/data.yml
Add line about FT scholarships and update enroll links.
> update scholarship copy and links

- bootcamps/thinkful/data.yml
Reverts Thinkful/bootcamp-finder#152
> Revert "update scholarship copy and links"

- bootcamps/thinkful/data.yml
> Add Los Angeles for Thinkful

- bootcamps/thinkful/data.yml
> add new cities

- bootcamps/thinkful/data.yml
> fix: PMF course length

- bootcamps/thinkful/data.yml
~Product Design Flex~ UX/UI Flex
> update bootcamp finder TF page with UX/UI info

- bootcamps/thinkful/data.yml
* Cleaning up the yml in this page to make it more consistent
* Updating naming convention from Flex to Flexible (compliance)
* Updating Engineering N&W pricing and program length
> fix: cleanup thinkful yml data
